# Linux kernel boot with default opensbi provided by QEMU
targets:
  main:
    drivers:
      QEMUDriver:
        qemu_bin: qemu-system-riscv64
        machine: virt
        cpu: rv64
        memory: '1G'
        kernel: kernel
        boot_args: 'earlycon=sbi console=ttyS0,115200'
        extra_args: '-smp 4 -netdev user,id=net0 -device virtio-net-device,netdev=net0'
      ShellDriver:
        name: 'test'
        login_prompt: " login: "
        prompt: "# "
        username: "root"
        password: "root"
      ShellStrategy: {}
images:
  kernel: !template $LG_IMAGES/$LG_LINUX

tools:
  qemu-system-riscv64: !template $LG_QEMU_RISCV64
